import React, { createContext, useContext, useState } from "react";
import { getLanguage, setLanguage } from "../services/lang";

type LangContextType = {
  lang: 'tr' | 'en';
  setLang: (lang: 'tr' | 'en') => void;
};

const LangContext = createContext<LangContextType | undefined>(undefined);

export const LangProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<'tr' | 'en'>(getLanguage());

  const setLang = (newLang: 'tr' | 'en') => {
    setLangState(newLang);
    setLanguage(newLang);
  };

  return (
    <LangContext.Provider value={{ lang, setLang }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be used within LangProvider");
  return ctx;
};

// translations.ts
export const translations: Record<'tr' | 'en', Record<string, string>> = {
  tr: {
    // General
    loading: "Yükleniyor...",
    noResults: "Sonuç bulunamadı",
    adjust: "Filtreleri değiştirerek tekrar deneyin.",
    Cancel: "İptal",
    Create: "Oluştur",
    Creating: "Oluşturuluyor…",
    Save: "Kaydet",
    Saving: "Kaydediliyor…",
    Edit: "Düzenle",
    Delete: "Sil",
    Update: "Güncelle",
    Actions: "İşlemler",
    Details: "Detaylar",
    Close: "Kapat",
    Yes: "Evet",
    No: "Hayır",
    Reset: "Sıfırla",
    Filter: "Filtrele",
    ApplyFilters: "Filtreleri Uygula",
    Search: "Ara",
    English: "English",
    Turkish: "Türkçe",

    // Sidebar & Navigation
    Dashboard: "Panel",
    Campaign: "Kampanya",
    Campaigns: "Kampanyalar",
    Reports: "Raporlar",
    GenerateLink: "Link Oluştur",
    Companies: "Şirketler",
    Influencers: "Influencerlar",
    Settings: "Ayarlar",
    Logout: "Çıkış Yap",

    // Login
    WelcomeBack: "Tekrar hoş geldiniz",
    SignInDashboard: "Ajans panelinize giriş yapın",
    Username: "Kullanıcı Adı",
    Password: "Şifre",
    RememberMe: "Beni hatırla",
    ForgotPassword: "Şifremi unuttum?",
    SignIn: "Giriş Yap",
    SigningIn: "Giriş yapılıyor...",
    LoginFailed: "Giriş başarısız.",
    SmartPlatform: "Akıllı Influencer Pazarlama Platformu",
    RealTimeAnalytics: "Gerçek zamanlı kampanya analitiği",
    AutomatedLink: "Otomatik link oluşturma",
    AdvancedReports: "Gelişmiş performans raporları",

    // Dashboard
    DashboardOverview: "Panel Özeti",
    DashboardDesc: "Affiliate pazarlama performansınızı ve kampanya metriklerinizi takip edin",
    Refresh: "Yenile",
    QuickLink: "Hızlı Link",
    ActiveCampaigns: "Aktif Kampanyalar",
    TotalClicks: "Toplam Tıklama",
    TotalSales: "Toplam Satış",
    TotalCompanyCommission: "Toplam Şirket Komisyonu",
    SalesPerformance: "Satış Performansı",
    PerformanceOverview: "Performans özeti",
    Last30Days: "Son 30 gün",
    Last7Days: "Son 7 gün",
    Last90Days: "Son 90 gün",
    RecentActivity: "Son Aktiviteler",

    // Campaigns
    CampaignsTitle: "Tüm kampanyalarınızı burada görüntüleyin ve yönetin.",
    NewCampaign: "Yeni Kampanya",
    SearchCampaign: "Kampanya ara...",
    AllStatus: "Tüm Durumlar",
    Active: "Aktif",
    Paused: "Durduruldu",
    Ended: "Bitti",
    Grid: "Grid",
    Table: "Tablo",
    CampaignName: "Kampanya Adı",
    BrandCommission: "Marka Komisyon Oranı:",
    InfluencerCommission: "Influencer Komisyon Oranı:",
    OtherCosts: "Diğer Masraf Oranları:",
    ViewDetails: "Detayları Gör",
    NameRequired: "İsim, Bitiş Tarihi ve Şirket zorunlu",
    Company: "Şirket",
    Brief: "Açıklama",
    BrandingImage: "Marka Görseli",
    EndDate: "Bitiş Tarihi",
    BrandCommissionRate: "Marka Komisyon Oranı (%)",
    InfluencerCommissionRate: "Influencer Komisyon Oranı (%)",
    OtherCostsRate: "Diğer Masraf Oranları (%)",
    Products: "Ürünler",
    Status: "Durum",
    Commission: "Komisyon",
    Performance: "Performans",
    Revenue: "Gelir",
    noCampaigns: "Hiç kampanya bulunamadı.",
    //adjust: "Filtreleri değiştirerek tekrar deneyin.",

    // Companies
    //Companies: "Şirketler",
    NewCompany: "Yeni Şirket",
    CompanyName: "Şirket Adı",
    Email: "E-posta",
    Phone: "Telefon",
    Address: "Adres",
    GSM: "GSM",
    Fax: "Faks",
    TaxOffice: "Vergi Dairesi",
    TaxNumber: "Vergi No",
    AuthorizedName: "Yetkili Adı",
    AuthorizedSurname: "Yetkili Soyadı",
    AuthorizedGSM: "Yetkili GSM",
    //Status: "Durum",
    //Active: "Aktif",
    Passive: "Pasif",
    CompanyDetail: "Şirket Detayı",
    CompanyEdit: "Şirket Düzenle",
    CompanyCreate: "Yeni Şirket",
    UserName: "Kullanıcı Adı",
    //Password: "Şifre",

    // Influencers
    //Influencers: "Influencerlar",
    NewInfluencer: "Yeni Influencer",
    InfluencerDetail: "Influencer Detayı",
    InfluencerEdit: "Influencer Düzenle",
    InfluencerCreate: "Yeni Influencer",
    DisplayName: "Görünen Ad",
    ProfileImage: "Profil Görseli",
    MLinkID: "MLink ID",
    UserID: "Kullanıcı ID",
    ResetPassword: "Şifre Sıfırla",
    ResetLinkCopied: "Şifre sıfırlama linki kopyalandı.",
    InfluencerRequired: "Kullanıcı adı, görünen ad ve e-posta zorunludur.",
    InfluencerCreated: "Influencer oluşturuldu.",
    InfluencerUpdated: "Influencer güncellendi",
    InfluencerUpdateFailed: "Güncelleme başarısız",
    InfluencerNotFound: "Influencer bulunamadı",
    FilterByUsername: "Kullanıcı adı ile ara",
    //Filter: "Filtrele",
    NoInfluencers: "Kayıt bulunamadı",
    DetailedListOfInfluencerReports: "Detaylı Influencer Raporları Listesi",

    // Reports
    PerformanceReports: "Performans Raporları",
    AnalyzePerformance: "Influencer performansını analiz edin ve komisyon dağılımını takip edin",
    ExportCSV: "CSV İndir",
    DateRange: "Tarih Aralığı",
    Influencer: "Influencer",
    AllInfluencers: "Tüm Influencerlar",
    //ApplyFilters: "Filtreleri Uygula",
    ActiveInfluencers: "Aktif Influencerlar",
    TotalInfluencerCommission: "Toplam Influencer Komisyonu",
    InfluencerReports: "Influencer Raporları",
    DetailedList: "Detaylı influencer rapor listesi",
    Clicks: "Tıklama",
    Sales: "Satış",
    ConvRate: "Dönüşüm Oranı",
    //Commission: "Komisyon",
    //Actions: "İşlemler",
    TopPerformers: "En İyi Performans Gösterenler",
    RevenueLeaders: "Gelir Liderleri",
    NoData: "Seçilen dönem için veri yok",
    ReportCreatedOn: "Rapor oluşturulma tarihi",
    Brand: "Marka",
    Mimeda: "Mimeda",
    Agency: "Ajans",
    Other: "Diğer",
    Breakdown: "Komisyon Dağılımı",
    Rates: "Oranlar",

    // Generate Link
    GenerateTrackingLink: "Takip Linki Oluştur",
    CreateTrackingLinks: "Influencer kampanyalarınız için özel takip linkleri oluşturun",
    SelectCampaign: "Kampanya seçin",
    SelectInfluencer: "Bir influencer seçin",
    NoInfluencersForCampaign: "Bu kampanya için influencer yok",
    SelectCampaignFirst: "Önce bir kampanya seçin",
    Selected: "Seçilen",
    //GenerateLink: "Link Oluştur",
    Generating: "Oluşturuluyor...",
    LinkGenerated: "Takip linki başarıyla oluşturuldu!",
    LinkCopied: "Link panoya kopyalandı!",
    FailedToCopy: "Link kopyalanamadı. Lütfen tekrar deneyin.",
    NextSteps: "Sonraki adımlar:",
    ShareTrackingLink: "Bu takip linkini {influencerName} ile paylaşın. Tüm tıklamalar ve dönüşümler otomatik olarak takip edilecektir.",

    // Settings
    //Settings: "Ayarlar",
    UpdateProfile: "Profil bilgilerinizi ve tercihlerinizi güncelleyin.",
    //DisplayName: "Görünen Ad",
    //Email: "E-posta",
    //Phone: "Telefon",
    NewPassword: "Yeni Şifre",
    ConfirmPassword: "Şifreyi Onayla",
    SaveChanges: "Değişiklikleri Kaydet",
    PasswordsDoNotMatch: "Şifreler eşleşmiyor",
    ProfileUpdated: "Profil başarıyla güncellendi",
    UpdateFailed: "Güncelleme başarısız",

    // Reset Password
    ResetPasswordTitle: "Şifre Sıfırla",
    PleaseFillAllFields: "Lütfen tüm alanları doldurun.",
    //PasswordsDoNotMatch: "Şifreler eşleşmiyor.",
    PasswordResetSuccess: "Şifre sıfırlandı. Giriş sayfasına yönlendiriliyorsunuz...",
    ErrorResettingPassword: "Şifre sıfırlanırken hata oluştu.",
    //NewPassword: "Yeni Şifre",
    //ConfirmPassword: "Şifreyi Onayla",
    Resetting: "Sıfırlanıyor...",
    //ResetPassword: "Şifreyi Sıfırla",

    // Toasts
    Success: "Başarılı",
    Error: "Hata",
    Warning: "Uyarı",
    CSVDownloaded: "CSV indirildi.",
    CSVDownloadFailed: "CSV indirilemedi.",
    FiltersApplied: "Filtreler başarıyla uygulandı",
    //WelcomeBack: "Tekrar hoş geldiniz! Başarıyla giriş yaptınız.",
    //LinkGenerated: "Takip linki başarıyla oluşturuldu!",
    //LinkCopied: "Link panoya kopyalandı!",
    FailedToGenerateLink: "Link oluşturulamadı",
    FailedToLoadCampaigns: "Kampanyalar yüklenemedi",
    FailedToLoadInfluencers: "Influencerlar yüklenemedi",
    FailedToLoadReports: "Raporlar yüklenemedi",
    FailedToLoadDashboard: "Panel verileri yüklenemedi",
    DashboardRefreshed: "Panel verileri başarıyla yenilendi",
    RedirectingToLinkGen: "Link oluşturucuya yönlendiriliyor...",
    ChooseTheCampaignThisLinkWillTrack: "Bu linkin takip edeceği kampanyayı seçin",
    MyPerformanceReports: "Kendi Performans Raporlarım",
    AnalyzeYourPerformance: "Kendi kampanya performansınızı analiz edin",
    MyReports: "Kampanya Raporlarım",
    YourCampaignPerformance: "Kampanyalarınızın performansını görüntüleyin"
  },

  en: {
    // General
    loading: "Loading...",
    noResults: "No results found",
    adjust: "Try adjusting your filters.",
    Cancel: "Cancel",
    Create: "Create",
    Creating: "Creating…",
    Save: "Save",
    Saving: "Saving…",
    Edit: "Edit",
    Delete: "Delete",
    Update: "Update",
    Actions: "Actions",
    Details: "Details",
    Close: "Close",
    Yes: "Yes",
    No: "No",
    Reset: "Reset",
    Filter: "Filter",
    ApplyFilters: "Apply Filters",
    Search: "Search",
    English: "English",
    Turkish: "Türkçe",

    // Sidebar & Navigation
    Dashboard: "Dashboard",
    Campaign: "Campaign",
    Campaigns: "Campaigns",
    Reports: "Reports",
    GenerateLink: "Generate Link",
    Companies: "Companies",
    Influencers: "Influencers",
    Settings: "Settings",
    Logout: "Logout",

    // Login
    WelcomeBack: "Welcome back",
    SignInDashboard: "Sign in to your agency dashboard",
    Username: "Username",
    Password: "Password",
    RememberMe: "Remember me",
    ForgotPassword: "Forgot password?",
    SignIn: "Sign in",
    SigningIn: "Signing in...",
    LoginFailed: "Login failed.",
    SmartPlatform: "Smart Influencer Marketing Platform",
    RealTimeAnalytics: "Real-time campaign analytics",
    AutomatedLink: "Automated link generation",
    AdvancedReports: "Advanced performance reports",

    // Dashboard
    DashboardOverview: "Dashboard Overview",
    DashboardDesc: "Track your affiliate marketing performance and campaign metrics",
    Refresh: "Refresh",
    QuickLink: "Quick Link",
    ActiveCampaigns: "Active Campaigns",
    TotalClicks: "Total Clicks",
    TotalSales: "Total Sales",
    TotalCompanyCommission: "Total Company Commission",
    SalesPerformance: "Sales Performance",
    PerformanceOverview: "Performance overview",
    Last30Days: "Last 30 days",
    Last7Days: "Last 7 days",
    Last90Days: "Last 90 days",
    RecentActivity: "Recent Activity",

    // Campaigns
    CampaignsTitle: "View and manage all your campaigns here.",
    NewCampaign: "New Campaign",
    SearchCampaign: "Search campaign...",
    AllStatus: "All Status",
    Active: "Active",
    Paused: "Paused",
    Ended: "Ended",
    Grid: "Grid",
    Table: "Table",
    CampaignName: "Campaign Name",
    BrandCommission: "Brand Commission Rate:",
    InfluencerCommission: "Influencer Commission Rate:",
    OtherCosts: "Other Costs Rate:",
    ViewDetails: "View Details",
    NameRequired: "Name, End Date and Company are required",
    Company: "Company",
    Brief: "Brief",
    BrandingImage: "Branding Image",
    EndDate: "End Date",
    BrandCommissionRate: "Brand Commission Rate (%)",
    InfluencerCommissionRate: "Influencer Commission Rate (%)",
    OtherCostsRate: "Other Costs Rate (%)",
    Products: "Products",
    Status: "Status",
    Commission: "Commission",
    Performance: "Performance",
    Revenue: "Revenue",
    noCampaigns: "No campaigns found.",
    //adjust: "Try adjusting your filters.",

    // Companies
    //Companies: "Companies",
    NewCompany: "New Company",
    CompanyName: "Company Name",
    Email: "Email",
    Phone: "Phone",
    Address: "Address",
    GSM: "GSM",
    Fax: "Fax",
    TaxOffice: "Tax Office",
    TaxNumber: "Tax Number",
    AuthorizedName: "Authorized Name",
    AuthorizedSurname: "Authorized Surname",
    AuthorizedGSM: "Authorized GSM",
    //Status: "Status",
    //Active: "Active",
    Passive: "Passive",
    CompanyDetail: "Company Detail",
    CompanyEdit: "Edit Company",
    CompanyCreate: "New Company",
    UserName: "Username",
    //Password: "Password",

    // Influencers
    //Influencers: "Influencers",
    NewInfluencer: "New Influencer",
    InfluencerDetail: "Influencer Detail",
    InfluencerEdit: "Edit Influencer",
    InfluencerCreate: "New Influencer",
    DisplayName: "Display Name",
    ProfileImage: "Profile Image",
    MLinkID: "MLink ID",
    UserID: "User ID",
    ResetPassword: "Reset Password",
    ResetLinkCopied: "Reset password link copied.",
    InfluencerRequired: "Username, display name and email are required.",
    InfluencerCreated: "Influencer created.",
    InfluencerUpdated: "Influencer updated",
    InfluencerUpdateFailed: "Update failed",
    InfluencerNotFound: "Influencer not found",
    FilterByUsername: "Search by username",
    //Filter: "Filter",
    NoInfluencers: "No records found",
    DetailedListOfInfluencerReports: "Detailed List of Influencer Reports",

    // Reports
    PerformanceReports: "Performance Reports",
    AnalyzePerformance: "Analyze influencer performance and track commission breakdowns",
    ExportCSV: "Export CSV",
    DateRange: "Date Range",
    Influencer: "Influencer",
    AllInfluencers: "All Influencers",
    //ApplyFilters: "Apply Filters",
    ActiveInfluencers: "Active Influencers",
    TotalInfluencerCommission: "Total Influencer Commission",
    InfluencerReports: "Influencer Reports",
    DetailedList: "Detailed list of influencer reports",
    Clicks: "Clicks",
    Sales: "Sales",
    ConvRate: "Conv. Rate",
    //Commission: "Commission",
    //Actions: "Actions",
    TopPerformers: "Top Performers",
    RevenueLeaders: "Revenue Leaders",
    NoData: "No data for the selected period",
    ReportCreatedOn: "Report created on",
    Brand: "Brand",
    Mimeda: "Mimeda",
    Agency: "Agency",
    Other: "Other",
    Breakdown: "Commission Breakdown",
    Rates: "Rates",

    // Generate Link
    GenerateTrackingLink: "Generate Tracking Link",
    CreateTrackingLinks: "Create custom tracking links for your influencer campaigns",
    SelectCampaign: "Select a campaign",
    SelectInfluencer: "Select an influencer",
    NoInfluencersForCampaign: "No influencers for this campaign",
    SelectCampaignFirst: "Select a campaign first",
    Selected: "Selected",
    //GenerateLink: "Generate Link",
    Generating: "Generating...",
    LinkGenerated: "Tracking link generated successfully!",
    LinkCopied: "Link copied to clipboard!",
    FailedToCopy: "Failed to copy link. Please try again.",
    NextSteps: "Next steps:",
    ShareTrackingLink: "Share this tracking link with {influencerName}. All clicks and conversions will be automatically tracked and attributed to their performance.",

    // Settings
    //Settings: "Settings",
    UpdateProfile: "Update your profile information and preferences.",
    //DisplayName: "Display Name",
    //Email: "Email",
    //Phone: "Phone",
    NewPassword: "New Password",
    ConfirmPassword: "Confirm Password",
    SaveChanges: "Save Changes",
    PasswordsDoNotMatch: "Passwords do not match",
    ProfileUpdated: "Profile updated successfully",
    UpdateFailed: "Update failed",

    // Reset Password
    ResetPasswordTitle: "Reset Password",
    PleaseFillAllFields: "Please fill in all fields.",
    //PasswordsDoNotMatch: "Passwords do not match.",
    PasswordResetSuccess: "Password reset successful. Redirecting to login...",
    ErrorResettingPassword: "Error resetting password.",
    //NewPassword: "New Password",
    //ConfirmPassword: "Confirm Password",
    Resetting: "Resetting...",
    //ResetPassword: "Reset Password",

    // Toasts
    Success: "Success",
    Error: "Error",
    Warning: "Warning",
    CSVDownloaded: "CSV downloaded.",
    CSVDownloadFailed: "CSV download failed.",
    FiltersApplied: "Filters applied successfully",
    //WelcomeBack: "Welcome back! Successfully logged in.",
    //LinkGenerated: "Tracking link generated successfully!",
    //LinkCopied: "Link copied to clipboard!",
    FailedToGenerateLink: "Failed to generate link",
    FailedToLoadCampaigns: "Failed to load campaigns",
    FailedToLoadInfluencers: "Failed to load influencers",
    FailedToLoadReports: "Failed to load reports",
    FailedToLoadDashboard: "Failed to load dashboard data",
    DashboardRefreshed: "Dashboard data refreshed successfully",
    RedirectingToLinkGen: "Redirecting to link generator...",
    ChooseTheCampaignThisLinkWillTrack: "Choose the Campaign This Link Will Track",
    MyPerformanceReports: "My Performance Reports",
    AnalyzeYourPerformance: "Analyze your campaign performance",
    MyReports: "My Campaign Reports",
    YourCampaignPerformance: "View your campaign performance"
  }
};


export function useT() {
  const { lang } = useLang();
  return (key: string) => (translations[lang][key] ?? key);
}

export function tWithVars(tmpl: string, vars: Record<string, string | number>) {
  return tmpl.replace(/\{(\w+)\}/g, (_, k) => vars[k] + '');
}